name: Build ms-love Linux AppImage

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CORE_LOVE_PACKAGE_PATH: ./build/game.love
  CORE_LOVE_ARTIFACT_NAME: core_love_package
  PRODUCT_NAME: ms-love
  BUNDLE_ID: com.example.ms-love
  OUTPUT_FOLDER: ./build

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build .love package
        uses: love-actions/love-actions-core@v1
        with:
          build-list: ./assets/ ./libs/ ./src/ ./main.lua ./conf.lua
          package-path: ${{ env.CORE_LOVE_PACKAGE_PATH }}

      - name: Upload core love package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}
          path: ${{ env.CORE_LOVE_PACKAGE_PATH }}
    
  build-linux:
    runs-on: ubuntu-latest
    needs: build-core

    steps:
    - uses: actions/checkout@v4

    - name: Download core love package
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}

    - name: Move love package to build folder
      run: |
        mkdir -p build
        mv game.love build/game.love

    - name: Build Linux AppImage
      uses: love-actions/love-actions-linux@v2
      with:
        app-name: ${{ env.PRODUCT_NAME }}
        product-name: ${{ env.PRODUCT_NAME }}
        bundle-id: ${{ env.BUNDLE_ID }}
        description: My LÖVE game
        version-string: "1.0.0"
        icon-path: ./assets/icons/ms-love.png
        love-package: ${{ env.CORE_LOVE_PACKAGE_PATH }}
        output-folder: ${{ env.OUTPUT_FOLDER }}

    - name: Upload Linux AppImage
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PRODUCT_NAME }}-Linux_AppImage
        path: ${{ env.OUTPUT_FOLDER }}/${{ env.PRODUCT_NAME }}.AppImage

  build-windows:
    runs-on: windows-latest
    needs: build-core

    steps:
      - uses: actions/checkout@v4

      - name: Download core love package
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}

      - name: Move love package to build folder
        run: |
          mkdir -p build
          mv game.love build/game.love

      - name: Build Windows packages
        uses: love-actions/love-actions-windows@v1
        with:
          love-package: ${{ env.CORE_LOVE_PACKAGE_PATH }}
          icon-path: ./assets/icons/favicon.ico
          product-name: ${{ env.PRODUCT_NAME }}
          output-folder: ${{ env.OUTPUT_FOLDER }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PRODUCT_NAME }}_x64
          path: ${{ env.OUTPUT_FOLDER }}/${{ env.PRODUCT_NAME }}_x64.zip
      
